### PR TITLE
Update release notes

### PR DESCRIPTION
**Pull request by robthomson**

### CODE REVIEW

**Comment by rotorflight** [comment]
There are no official releases from this repo, so this file should only have the release note for the fortcomint 2.1.0-RC1

**Comment by robthomson** [comment]
Updated..

**Review by ghost — CHANGES_REQUESTED** [review]
The next release is 2.1.0-RC1 NOT 2.0.0-RC1
Also
please consider if you want to say something about the Lua suite, rather than Rotorflight in general.
This text is from the firmware, which is shown in the Flasher, thus it is a bit more generic.

**Comment by robthomson** [comment]
Done!

**Review by ghost — CHANGES_REQUESTED** [review]
Still need to change the version number in the code to match 2.1.0-RC1

**Comment by robthomsonb4b** [comment]
Do you mean in the code of main.lua ?

I was going to do that that but you thought you said to hold off?

**Comment by robthomson** [comment]
Added a second PR for the version number bump in main.lua

**Pull request closed without merging**
