### PR TITLE
Relative Paths

### PR DESCRIPTION
**Pull request by robthomson**
It has proven impossible to manage compilation of the lua scripts dynamically on the fly.  

This commit strips out compilation

essentially..  replace compile.loadFile with loadfile

Included in this commit is the use of relative pathing. 

This 2 step change has resulted in complete ethos 1.6 compatability.

### CODE REVIEW

**Comment by rotorflight** [comment]
The title says "Relative paths", but the description says "This commit strips out compilation" ?

**Comment by robthomson** [comment]
Yes.   It was part of same job.

Essentially while moving to relative paths I found that it was utterly impossible without removing compilation.

So batches it into the same commit.

**Comment by robthomson** [comment]
I could do it as two commits.. But they are dependant on each other.

**Comment by rotorflight** [comment]
Do them in the dependency order

**Pull request closed without merging**
